spring.application.name=MyApi
server.port=8080
## self explanatory

spring.datasource.url = jdbc:mysql://localhost:8080/mydatabase
## to view the database "online" or through the port.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## the driver class to let jdbc know which connection to use or how to connect to the database connected

spring.jpa.show-sql: true
## can see the query in the terminal
spring.jpa.hibernate.ddl-auto=update  
## the above is used so that the jpa updates the database if it already exists so that it doesnt create a new one every time we rerun the model.
